[2025-02-02T01:15:37.109+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.generate_ingestion_data manual__2025-02-02T01:15:35.242057+00:00 [queued]>
[2025-02-02T01:15:37.120+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.generate_ingestion_data manual__2025-02-02T01:15:35.242057+00:00 [queued]>
[2025-02-02T01:15:37.120+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-02-02T01:15:37.134+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): generate_ingestion_data> on 2025-02-02 01:15:35.242057+00:00
[2025-02-02T01:15:37.141+0000] {standard_task_runner.py:57} INFO - Started process 1601 to run task
[2025-02-02T01:15:37.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'generate_ingestion_data', 'manual__2025-02-02T01:15:35.242057+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/upstreams_data_ingestion_pipeline.py', '--cfg-path', '/tmp/tmps1nqfkam']
[2025-02-02T01:15:37.148+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask generate_ingestion_data
[2025-02-02T01:15:37.192+0000] {task_command.py:410} INFO - Running <TaskInstance: ingestion_pipeline.generate_ingestion_data manual__2025-02-02T01:15:35.242057+00:00 [running]> on host 5bf3ecbe28c2
[2025-02-02T01:15:37.257+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='generate_ingestion_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T01:15:35.242057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T01:15:35.242057+00:00'
[2025-02-02T01:15:37.264+0000] {spark_submit.py:218} INFO - Could not load connection string spark_local, defaulting to yarn
[2025-02-02T01:15:37.265+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.instances=4 --conf spark.executor.memory=4g --conf spark.driver.memory=2g --conf spark.sql.shuffle.partitions=8 --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --name arrow-spark --verbose /opt/***/dags/upstreams_data_ingestion_pipeline.py
[2025-02-02T01:15:37.295+0000] {spark_submit.py:490} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-02-02T01:15:37.296+0000] {spark_submit.py:490} INFO - /opt/spark/bin/spark-class: line 97: CMD: bad array subscript
[2025-02-02T01:15:37.308+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.instances=4 --conf spark.executor.memory=4g --conf spark.driver.memory=2g --conf spark.sql.shuffle.partitions=8 --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --name arrow-spark --verbose /opt/***/dags/upstreams_data_ingestion_pipeline.py. Error code is: 1.
[2025-02-02T01:15:37.313+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=ingestion_pipeline, task_id=generate_ingestion_data, execution_date=20250202T011535, start_date=20250202T011537, end_date=20250202T011537
[2025-02-02T01:15:37.323+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 35 for task generate_ingestion_data (Cannot execute: spark-submit --master yarn --conf spark.executor.instances=4 --conf spark.executor.memory=4g --conf spark.driver.memory=2g --conf spark.sql.shuffle.partitions=8 --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 --name arrow-spark --verbose /opt/***/dags/upstreams_data_ingestion_pipeline.py. Error code is: 1.; 1601)
[2025-02-02T01:15:37.362+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-02T01:15:37.382+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
